apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: nodeport
  selector:
    app: java-app
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 8080
